name: Deploy to k8s
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: deploy
        run: |
          ls
          kubectl apply -f manifest.yaml
          
